single-thread-pipeline:
  delay: 10
  workers: 4
  source:
    in_memory:
      testing_key: SingleThreadProcessorIT

  buffer:
    bounded_blocking:
      buffer_size: 1000
      batch_size: 10

  processor:
    - single_thread_test:

  sink:
    - in_memory:
        testing_key: SingleThreadProcessorIT
